# -*- coding: utf-8 -*-
"""q1_vendor_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHpoznm5yEu3kr_YBkeAHl6oXR56SpjF
"""

import time
time.sleep(0.5)

mock_db = {
    "V001" : {"name": "Alpha Corp", "rating": 4.5},
    "V002" : {"name": "Beta Corp", "rating": 3.8},
    "V004" : {"name": "Gamma Corp", "rating": 4.9}
}

def fetch_vendor_data(vendor_ids):
  retrieved_vendors = {}

  for vendor_id in vendor_ids:
      if vendor_id in mock_db:
          retrieved_vendors[vendor_id] = mock_db[vendor_id]
      else:
          print(f"Vendor ID {vendor_id} not found.")
  return retrieved_vendors

vendor_list = ["V001", "V002", "V003", "V004"]
result = fetch_vendor_data(vendor_list)
print(result)