# -*- coding: utf-8 -*-
"""q5_invoice_extraction_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t74GgPffUG328UzSNPyytAjsWZX_GXbT
"""

import re

invoice_text = """
Invoice Number: INV-2024-001
Invoice Date: 12-07-2026
Vendor Name: Alpha Technologies Pvt Ltd
Total Amount: ₹12500
"""

def extract_invoice_fields(text):

    extracted_data = {}

    invoice_number = re.search(
        r'Invoice Number:\s*(.*)',
        text
    )

    invoice_date = re.search(
        r'Invoice Date:\s*(.*)',
        text
    )

    vendor_name = re.search(
        r'Vendor Name:\s*(.*)',
        text
    )

    total_amount = re.search(
        r'Total Amount:\s*₹?(\d+)',
        text
    )

    extracted_data["invoice_number"] = (
        invoice_number.group(1)
        if invoice_number else None
    )

    extracted_data["invoice_date"] = (
        invoice_date.group(1)
        if invoice_date else None
    )

    extracted_data["vendor_name"] = (
        vendor_name.group(1)
        if vendor_name else None
    )

    extracted_data["total_amount"] = (
        total_amount.group(1)
        if total_amount else None
    )

    return extracted_data


def validate_fields(data):

    mandatory_fields = [
        "invoice_number",
        "invoice_date",
        "vendor_name",
        "total_amount"
    ]

    missing_fields = []

    for field in mandatory_fields:
        if not data[field]:
            missing_fields.append(field)

    return missing_fields


result = extract_invoice_fields(invoice_text)

print("Extracted Data:")
print(result)

missing = validate_fields(result)

if len(missing) == 0:
    print("\nValidation Successful")
    print("Data stored in procurement database")

else:
    print("\nFallback Triggered")
    print("Missing fields:", missing)
    print("Document moved to manual review queue")